### ISSUE TITLE
Opera for Android support?

### ISSUE THREAD

**Issue by mathiasbynens** [WebReflection/testardo#1]
Really nice work on this project!

Any plans to support [Opera for Android](http://www.opera.com/mobile/android)?

**Comment by WebReflection** [comment]
Mini or Mobile or both? Any specific issue? I simply had no time to check but I surely want them to be part of the targets … ideally I want no browser left out.

**Comment by mathiasbynens** [comment]
Both would be even better. Opera for Android (i.e. Mobile) is probably easiest to test, though :)

> I simply had no time to check but I surely want them to be part of the targets … ideally I want no browser left out.

Good to know!

**Comment by WebReflection** [comment]
I've tested right now Opera Mobile Classic and it works without problems.

**Comment by WebReflection** [comment]
P.S. it's very unfortunate Opera Mini does not seem to work with intranet addresses … I kinda understand why but that also sucks, development speaking :-(
