### ISSUE TITLE
Google demo isnt work on iPhone Os7

### ISSUE THREAD

**Issue by rubelux** [WebReflection/testardo#5]
I love this project, I think it has an amazing potential,
Unfortunately the google example doesnt work on iPhone Os7.

Do I have to do any extra configuration?
Thank you

**Comment by WebReflection** [comment]
thanks @rubelux , glad you liked it. I have a demo today so I'll try to test and fix that example that was indeed failing in the video I've made too :-)

However, please have a look to the sandbox API (in comments) and feel free to start playing with it. Remember the ideal scenario for testardo is your localhost/intranet project but there's still a lot to improve/add/test with testardo and well, I'll use testardo to test testardo as well so stay tuned ;-)

**Comment by WebReflection** [comment]
actually, it does work on my iPod on iOS7 … I am using this command line

`testardo --host=google.com examples/google-search.js`

reaching my Mac through `http://192.168.1.27:7357/$` and I had to write the whole thing, including `http://` before the IP and `/$` at the end.

What happens in your case? Thanks

**Comment by WebReflection** [comment]
ok, I will close this but if you keep having problems with the latest version please let me know, thanks.

**Comment by rubelux** [comment]
sorry Andrea, I didnt have time to try it out, I will today and let you know
