### ISSUE TITLE
Testardo logo

### ISSUE THREAD

**Issue by GianlucaGuarini** [WebReflection/testardo#6]
I've made a simple logo for testardo nothing too complicated but at least something that eventually could be used for a custom flat website. Looking for a feedback

![testardo-logo_01](https://f.cloud.github.com/assets/879612/2057467/ff2506d4-8b30-11e3-88dc-d10dcb54f024.png)
![testardo-logo_02](https://f.cloud.github.com/assets/879612/2057468/01f29066-8b31-11e3-9812-2b660cb8d7d1.png)

**Comment by WebReflection** [comment]
OMFG … THIS IS AWESOME!!!
