### ISSUE TITLE
HTTP headers are not forwarded to web server

### ISSUE THREAD

**Issue by ghost** [WebReflection/testardo#9]
When I add "--host=example.com" the http request gets sent to my servers IP address without any http headers, the default site setup in IIS therefore hijacks this request. 

With multiple sites hosted in IIS that I wish to test, is there a workaround to send at least the http Host header?

thanks

**Comment by WebReflection** [comment]
at the beginning I was forwarding all headers mixing them with those defaulted via node get proxy … and I had the opposite problem, Apache and nginx were rejecting these requests.

Would you mind telling me which header you think IIS needs in order to not hijacks these requests?

**Comment by ghost** [comment]
Yep. Seems like it's:

``` http
Host: example.com
```

IIS uses this to determine which site to direct the request to. Thanks for the quick reply and for this great tool I appreciate the work you are doing here! - it's much easier to test cross browser than Selenium :) 

Here's an example of Request Headers to confirm:

``` http
Accept:text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding:gzip,deflate,sdch
Accept-Language:en-US,en;q=0.8
Cache-Control:no-cache
Connection:keep-alive
Host:example.com
Pragma:no-cache
User-Agent:Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.3 Safari/537.36
```

**Comment by WebReflection** [comment]
so I am actually sending browser headers when no HTTPS is involved … trying to investigate why example.com gives me a not found back :-/

**Comment by ghost** [comment]
Ok so I confess my website wasn't example.com it's justchecking.co.uk I was
just using the example.com domain as an example :/

Anyhow, the DNS lookup fetches the correct IP. (94.229.170.200) but as iis
has a default site set to \* ip addresses, and with no host header sent, iis
tries to direct to that default site which actually has no content. You can
try this yourself by navigating to http://94.229.170.200 (results in a 403
as no content exists for the default site) and
http://www.justchecking.co.uk(which works in a browser) to see the
different sites, even though they are
both hosted on a single IP.

Does this make a bit more sense?

Thanks!

On Friday, 21 February 2014, Andrea Giammarchi notifications@github.com
wrote:

> so I am actually sending browser headers when no HTTPS is involved ...
> trying to investigate why example.com gives me a not found back :-/
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/WebReflection/testardo/issues/9#issuecomment-35782425
> .

## 

Many thanks,
Jonathan Rowley

**Comment by WebReflection** [comment]
Please verify **v0.2.5** against `example.com` … it works for me and the problem was the missing `host` in the headers.

Feel free to close after that, thank you!

**Comment by WebReflection** [comment]
read the message now … no, if you are in HTTP and **not** HTTPS headers are sent exactly as the browser would do. The host needed an override though, so please check if it's OK now. Thanks

**Comment by ghost** [comment]
Great. Just tested and all working fine. I have noticed that if the site has a redirect that the host page gets updated. eg. host specified as "justchecking.co.uk" -> 301 redirects to www.justchecking.co.uk which causes a security exception in Opera 12.16 and the other browsers just load a blank page.
Do you want me to open a new issue for this?

Thanks for being so quick at responding!

**Comment by WebReflection** [comment]
I rather focus on something else since you can just specify a www as host directly without problems, right?

**Comment by ghost** [comment]
Yes you can just add the 'www' subdomain but I thought it might be something to notify people of in the docs or put a fix in the code for redirects? - can I add make a pull request and add to the readme?

thanks

**Comment by WebReflection** [comment]
right … ideally redirects should be handled without problems so please file a bug instead, thanks :-)

**Comment by WebReflection** [comment]
FYI, in order to force the host header you now need to specify `--force-host` when you launch `testardo`. This is because of [this regression](https://github.com/WebReflection/testardo/pull/10) introduced for all others non IIS servers. I should have tested that, oh …. irony!

Apologies for any inconvenience

**Comment by ghost** [comment]
Oh, this is the issue with the redirects... You need to specify the exact
domain name otherwise if the server 301 redirects you then testardo falls
over. The use of the host name presents this issue so adding that new flag
will be a temporary fix.

On Thursday, 27 February 2014, Andrea Giammarchi notifications@github.com
wrote:

> FYI, in order to force the host header you now need to specify
> --force-host when you launch testardo. This is because of this regressionhttps://github.com/WebReflection/testardo/pull/10introduced for all others non IIS servers. I should have tested that, oh ....
> irony!
> 
> Apologies for any inconvenience
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/WebReflection/testardo/issues/9#issuecomment-36304371
> .

## 

Many thanks,
Jonathan Rowley
